language: python
python:
  - "3.4"

before_install:
  - "nvm install node"
  - "nvm use node"
  - "npm install -g node-qunit-phantomjs"
install: "pip install -r requirements.txt"
script:
  - py.test
  - node-qunit-phantomjs tests/js/run_tests.html

notifications:
  email:
    on_success: change
    on_failure: always
