language: python
python:
  - "3.4"
  - "3.6"

services:
  - mongodb

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add parcel-bundler
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls pytest-cov"
  - "pip install coverage --upgrade"
  - "yarn install"

script:
  - py.test tests/ -v --cov reporting_app --cov rest_api --cov-report term-missing
  - yarn test
  - yarn build

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: always
