language: python
python:
  - "3.4"

before_install:
  - "nvm install node"
  - "nvm use node"
  - "npm install -g node-qunit-phantomjs"
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls pytest-cov"
script:
  - py.test tests/ -v --cov reporting_app --cov rest_api --cov-report term-missing
  - node-qunit-phantomjs tests/js/run_tests.html
after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: always
