runs:
    run_id: {                   type: 'string',  required: True,  unique: True }
    number_of_lanes: {          type: 'integer', required: False, min: 1, max: 8 }  # [1..8]
    run_elements: {             type: 'list',    required: False, schema: {type: 'string', data_relation: {resource: 'run_elements', field: 'run_element_id', embeddable: True } } }


lanes:
    lane_id: {                  type: 'string',  required: True,  unique: True}
    run_id: {                   type: 'string',  required: False }
    lane_number: {              type: 'integer', required: False, min: 1, max: 8 }
    run_elements: {             type: 'list',    required: False, schema: {type: 'string', data_relation: {resource: 'run_elements', field: 'run_element_id', embeddable: True } } }


run_elements:
    run_element_id: {           type: 'string',  required: True,  unique: True }

    run_id: {                   type: 'string',  required: True }
    lane: {                     type: 'integer', required: True }
    barcode: {                  type: 'string',  required: True }
    project_id: {               type: 'string',  required: True }

#   for now, treat sample_id and library_id as 1:1 equivalent
    library_id: {               type: 'string',  required: True }
    sample_id: {                type: 'string',  required: True }

    total_reads: {              type: 'integer', required: False }
    passing_filter_reads: {     type: 'integer', required: False }
    pc_reads_in_lane: {         type: 'float',   required: False }

    bases_r1: {                 type: 'integer', required: False }
    q30_bases_r1: {             type: 'integer', required: False }
    bases_r2: {                 type: 'integer', required: False }
    q30_bases_r2: {             type: 'integer', required: False }

    fastqc_report_r1: {         type: 'string',  required: False }
    fastqc_report_r2: {         type: 'string',  required: False }

    reviewed: {                 type: 'string',  required: False, allowed: ['not reviewed', 'pass', 'force', 'fail'] }


unexpected_barcodes:
    run_element_id: {           type: 'string',  required: True,  unique: True }

    run_id: {                   type: 'string',  required: True }
    lane: {                     type: 'integer', required: True }
    barcode: {                  type: 'string',  required: True }
    passing_filter_reads: {     type: 'float',   required: False }
    pc_reads_in_lane: {         type: 'float',   required: False }


projects:
    project_id: {               type: 'string',  required: True,  unique: True}
    samples: {                  type: 'list',    required: False, schema: {type: 'string', data_relation: {resource: 'samples', field: 'sample_id', embeddable: False } } }


samples:
    library_id: {               type: 'string',  required: True  }
    project_id: {               type: 'string',  required: True  }
    sample_id: {                type: 'string',  required: True,  unique: True }
    user_sample_id: {           type: 'string',  required: False }

#   initial reads used to be 'no adaptor reads'. Get yield_in_gb by embedding a run_element
    bam_file_reads: {           type: 'integer', required: False }  # reads initially found in the bam file
    mapped_reads: {             type: 'integer', required: False }
    properly_mapped_reads: {    type: 'integer', required: False }
    duplicate_reads: {          type: 'integer', required: False }
    median_coverage: {          type: 'float',   required: False }
    pc_callable: {              type: 'float',   required: False }  # aggregate pc_q30 from embedded run elements

    run_elements: {             type: 'list',    required: False, schema: {type: 'string', data_relation: {resource: 'run_elements', field: 'run_element_id', embeddable: True } } }
    reviewed: {                 type: 'string',  required: False, allowed: ['not reviewed', 'pass', 'fail'] }
