
rest_app:
    key: 'a_test_key'
    webserver: tornado
    port: 80

    db_name: 'edgen_reporting'
    db_host: 'mongodb://localhost'
    db_port: 27017

    x_domains: []
    url_prefix: 'api'
    api_version: '0.1'
    timed_rotating_file_handlers:
        - filename: /opt/logs/rest_api.log
          when: 'midnight'
          level: INFO

    lims_database:
        database_type: sqlite
        database_path: /opt/clarity_lims_database.sqlite

    available_coverages: [10, 15, 30, 60, 90, 120]
    available_yields:
        40: 35
        60: 52.5
        120: 105
        240: 210
        360: 315
        480: 420


reporting_app:  # only need this in the image for the user_db
    key: 'a_test_key'
    user_db: /opt/users.sqlite
